### ISSUE TITLE
HA ADDON: How do I add two devices?

### ISSUE THREAD

**Issue by sohsatoh** [jeremywillans/ha-rest980-roomba#10]
Hi!
First, thank you for the great configuration and its tutorial!

I have two iRobot devices - Roomba 980 and Braava jet m6, so I have added your rest980 Docker Image and rest980_2 Docker Image and other components on my HA.

The question is, how do I change the yaml file to make the two devices work together?

**Comment by sohsatoh** [comment]
Sorry, solved!

**Comment by jeremywillans** [comment]
Glad its solved! Do you think the repo needs some clarification on how to achieve this? If you have some high level steps I can add an entry in the FAQ to help others in future :)

**Comment by clipse2004** [comment]
Hello,
i have the same question, how can i use two robots? I need a complete second configuration right? my first one works but the second one not :/
