### ISSUE TITLE
Roombapw docker image doesnt install in home assistant

### ISSUE THREAD

**Issue by dylanmcdermott** [jeremywillans/ha-rest980-roomba#12]
It gets stuck trying to install and then nothing happens.

**Comment by jeremywillans** [comment]
Do you get anything in the logs ?

**Comment by jeremywillans** [comment]
Bump - any update?

**Comment by jeremywillans** [comment]
Closed no response.

**Comment by allanak** [comment]
Had the same issue. Here's a dump from hassio_supervisor log:

> 21-01-02 01:34:34 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build 39c40414/amd64-addon-roombapw:1.0.0: The command '/bin/sh -c npm install' returned a non-zero code: 1
> 21-01-02 01:34:34 ERROR (SyncWorker_6) [supervisor.docker.addon] Build log:
> Step 1/16 : FROM node:alpine
> 
> 
>  ---> 5304e0d27d98
> 
> Step 2/16 : RUN mkdir -p /usr/src/app
> 
> 
>  ---> Using cache
> 
>  ---> 625c82690dc1
> 
> Step 3/16 : WORKDIR /usr/src/app
> 
> 
>  ---> Using cache
> 
>  ---> 65ca28b51895
> 
> Step 4/16 : ENV NODE_ENV production
> 
> 
>  ---> Using cache
> 
>  ---> 344bf257513e
> 
> Step 5/16 : COPY package.json /usr/src/app/
> 
> 
>  ---> Using cache
> 
>  ---> e107042f947a
> 
> Step 6/16 : RUN npm install
> 
> 
>  ---> Running in 253e3ba4a2bb
> 
> npm
>  ERR!
> code ERESOLVE
> 
> npm
> ERR! Cannot destructure property 'name' of 'node' as it is null.
> 
> 
> 
> npm
> ERR!
>  A complete log of this run can be found in:
> npm ERR!
>      /root/.npm/_logs/2021-01-02T01_34_33_353Z-debug.log
