### ISSUE TITLE
Support Zones with ZoneIDs?

### ISSUE THREAD

**Issue by Kev1000000** [jeremywillans/ha-rest980-roomba#13]
With the new Zone support (regions within regions), I would love to be able to trigger this via Home Assistant!

It appears the only difference between Zones and Regions is the `type` property.  Regions are `rid` while Zones are `zid`

![image](https://user-images.githubusercontent.com/4720239/99886350-cec0c600-2c09-11eb-8ba3-b5e35b7ccde0.png)

**Comment by jeremywillans** [comment]
It should be as simple as defining a secret/input_boolean/input_text and updating the existing secrets to re-incorporate the "type" field. Ill try get some time to test soon and merge it in

**Comment by Kev1000000** [comment]
Awesome, that would be great!  Thank you!

**Comment by joshuakohut77** [comment]
Has there been any update on this? Please don't feel rushed, just following up. Thank you so much for all your hard work!

**Comment by jeremywillans** [comment]
Done - 0.9 Release 👍
