### ISSUE TITLE
nginx setup

### ISSUE THREAD

**Issue by Scheidegger** [jeremywillans/ha-rest980-roomba#16]
I have tried installing php-nginx Docker Image through the supervisor. I kept the standard config with NGINX_WEBROOT: /config/vacuum

I use Hass.io on a Synology Diskstation. The homeassistant version does not have a standard 'config' directory. I did create a directory '/config/vacuum' in /Hass.io/hass.io/homeassistant

When I start nginx I get the following error:

rendered 1 template(s) with 0 error(s) in 553.713µs
> chown webroot files
find: /config/vacuum: No such file or directory
./setup: line 51: pushd: /config/vacuum: No such file or directory
./setup: line 87: popd: directory stack empty
> starting php service
[12-Dec-2020 18:17:08] ERROR: [pool www] the chdir path '/config/vacuum' does not exist or is not a directory
[12-Dec-2020 18:17:08] ERROR: [pool www] the chdir path '/config/vacuum' does not exist or is not a directory
[12-Dec-2020 18:17:08] ERROR: failed to post process the configuration
[12-Dec-2020 18:17:08] ERROR: failed to post process the configuration
[12-Dec-2020 18:17:08] ERROR: FPM initialization failed
[12-Dec-2020 18:17:08] ERROR: FPM initialization failed
> writing php config
gomplate version 3.1.0, build 2f357bd5 (2018-11-30T02:51:11Z)
config is:
> writing fpm config
input: /etc/templates/php.ini.tmpl
output: /etc/php7/php.ini

Any advice how to connect the internal docker directory properly with the homeassistant directory in order to make it work?

Thanks.

Cheers
Patrick

**Comment by jeremywillans** [comment]
Hi Patrick,

You should only need to have the vacuum folder inside "homeassistant". If you deployed HA (formerly HASS) not on Synology, then the homeassistant folder would be "config"

So put the vacuum folder inside homeassistant and update the enviro variable to - 

NGINX_WEBROOT: /Hass.io/hass.io/homeassistant/vacuum

**Comment by Scheidegger** [comment]
> Hi Patrick,
> 
> You should only need to have the vacuum folder inside "homeassistant". If you deployed HA (formerly HASS) not on Synology, then the homeassistant folder would be "config"
> 
> So put the vacuum folder inside homeassistant and update the enviro variable to -
> 
> NGINX_WEBROOT: /Hass.io/hass.io/homeassistant/vacuum

Thanks for swift reply. I did that too - was my original thinking - but unfortunately it does not seem to work still.
> starting php service
[14-Dec-2020 08:41:10] ERROR: [pool www] the chdir path '/Hass.io/hass.io/homeassistant/vacuum' does not exist or is not a directory
[14-Dec-2020 08:41:10] ERROR: [pool www] the chdir path '/Hass.io/hass.io/homeassistant/vacuum' does not exist or is not a directory
> writing php config
[14-Dec-2020 08:41:10] ERROR: failed to post process the configuration
[14-Dec-2020 08:41:10] ERROR: failed to post process the configuration
[14-Dec-2020 08:41:10] ERROR: FPM initialization failed
[14-Dec-2020 08:41:10] ERROR: FPM initialization failed
gomplate version 3.1.0, build 2f357bd5 (2018-11-30T02:51:11Z)
config is:
input: /etc/templates/php.ini.tmpl
output: /etc/php7/php.ini

I stil get the path error. Seems to me to have something to do with the mapping from docker to the host system?

Regards
Patrick

**Comment by jeremywillans** [comment]
Ok can you please provide the following
- your current mapping config
- the full path on your syno

**Comment by NCGNConsulting** [comment]
Hi @jeremywillans ,

I'm experiencing some issues, maybe you can help me.

[19-Jan-2021 09:26:06] ERROR: [pool www] the chdir path '/config/vacuum' does not exist or is not a directory
[19-Jan-2021 09:26:06] ERROR: [pool www] the chdir path '/config/vacuum' does not exist or is not a directory
find: /config/vacuum: No such file or directory
./setup: line 51: pushd: /config/vacuum: No such file or directory
./setup: line 87: popd: directory stack empty


Add-on config NGINX_WEBROOT: /config/vacuum

Docker home assistant directory:

/usr/share/hassio/homeassistant | mapped to /config

nginx container too:
/usr/share/hassio/homeassistant | mapped to /config


deployed files in /usr/share/hassio/homeassistant/config/vacuum and tried it also in /usr/share/hassio/homeassistant/**www**/config/vacuum

restarting add-on, and still same message.

What I'm doing wrong?.

Thank you.

**Comment by Scheidegger** [comment]
Hi
I did the mistake that I thought I had to adapt the path to my specific setup whereas in the secrets.yaml I should have kept the standard path: 
vacuum_log: /config/vacuum/vacuum.log
vacuum_dir: /config/vacuum

(on my host system that sits in /Hass.io/homeassistant/vacuum)

I am using container koalazak-rest980 and made sure container can access file system on host environment. In my case Synology NAS.

Hope that helps.
Cheers
Patrick

**Comment by jeremywillans** [comment]
@NCGNConsulting

> deployed files in /usr/share/hassio/homeassistant/config/vacuum

change this to /usr/share/hassio/homeassistant/vacuum

Otherwise you are referring to it as /config/config/vacuum from the perspective of the php-nginx container 👍

**Comment by jeremywillans** [comment]
Bump

**Comment by NCGNConsulting** [comment]
Thank you Jeremy,

I will have a look. Unfortunatelly I can't dedicate time to it, and need to reinstall my pi.
As soon as I have homeassistant working properly, I will add it again.
I will let you know.
Regards.

**Comment by jeremywillans** [comment]
Closing. Please raise a new issue if required in future.
