### ISSUE TITLE
IDEA: Do logs on a per room/area basis

### ISSUE THREAD

**Issue by boelle** [jeremywillans/ha-rest980-roomba#21]
This would allow for smaller log files in big houses/flats

Doing 2 pass cleaning can create a big log if you do a clean all
If it was split up it would not take as long before the map could be drawn, of course in the end it would mabe be the same

but too see something happen faster would be nice i think

**Comment by jeremywillans** [comment]
The map should be drawn in realtime as the log is created. Does this not happen for you?

**Comment by boelle** [comment]
Nope

Its very slow when it happens. Sometimes it never happens but the log is
created thou

Using a raspi 3 to run ha

søn. 21. feb. 2021 23.46 skrev Jeremy Willans <notifications@github.com>:

**Comment by jeremywillans** [comment]
My map is redrawn throughout the cleaning process, try opening the image.php file locally in your browser and refresh to see if it actaully is getting drawn ?

**Comment by boelle** [comment]
it did draw one time

the next it got me:

502 Bad Gateway
nginx/1.16.1

when it did draw i feel'ed it was a bit slow but not totally bad

**Comment by boelle** [comment]
if i use shift+f5 then i dont get the bad gateway error

and going to image.php is actually a good trick to adjust the settings in image.php a bit faster

i did save my logs on a per rooms basis for just that purpose. kitchen is now spot on and will do all the other rooms

But i still think my idea is valid for big houses where the log files becomes large

**Comment by boelle** [comment]
i started an all room cleaning and before that i wiped the vacum log and the images it creates

so far it has not populated the map

its a 2 pass clean so it will take the better part of 2-3 hours and it will have to charge at some point

**Comment by jeremywillans** [comment]
I can watch my map get re-drawn in real time, i think this is likely more an issue with avaialble processing capability of the RPi3.

Short of cleaning the rooms individually, there isn't really any way of "breaking" up the log file during the clean. The API does not give any details of current room being cleaned, so cant work out where to split it.

**Comment by boelle** [comment]
> d, so cant work out where to split it.

i hoped for that, but yes i also think its the pi3 that is kind of underpowered

but still thanks for the tip on going to image.php directly... it seems to work when it does draw
