### ISSUE TITLE
Connection error trying to retrieve blind and password

### ISSUE THREAD

**Issue by caliKev** [jeremywillans/ha-rest980-roomba#23]
I’m getting the following error using software 2021.3.4

`
> dorita980@3.1.7 getpassword /usr/src/app
> node ./bin/getpassword.js
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
This step will continue in 10 seconds...
(node:25) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: connect EHOSTUNREACH 192.168.86.5:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 8883
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dorita980@3.1.7 getpassword: `node ./bin/getpassword.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dorita980@3.1.7 getpassword script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-31T14_18_07_838Z-debug.log`

**Comment by jeremywillans** [comment]
EHOSTUNREACH - this is indicating that the add-on is unable to reach the IP Address of your roomba (being 192.168.86.5)

are you sure this is correct?

**Comment by jeremywillans** [comment]
Bump

**Comment by Linxory** [comment]
Had the same, in the manual is stated "do not run the app when performing this step", wanted to add, when you have the Roomba Integration Passively installed in HA - does not start up either, as this is also polling MQTT data. Roomba's only have 1 active MQTT connection line available, from what I understood. So disabling or removing this might also solve the issue.

**Comment by BackedUpBooty** [comment]
> when you have the Roomba Integration Passively installed in HA - does not start up either, as this is also polling MQTT data. Roomba's only have 1 active MQTT connection line available

100% this. Couldn't figure out why I was getting an ERRCONNREFUSED and this was the solution
