### ISSUE TITLE
rest980 Docker Image Start error

### ISSUE THREAD

**Issue by astranberg** [jeremywillans/ha-rest980-roomba#24]
Hey,

I'm getting this error when starting the rest980 via HA Add-on store.

```
> rest980@2.1.0 start /usr/src/app
> node ./bin/www
/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7
  throw new Error('Not implemented.');
  ^
Error: Not implemented.
    at dorita980 (/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7:9)
    at new cloud (/usr/src/app/node_modules/dorita980/index.js:12:10)
    at /usr/src/app/routes/api.js:33:46
    at handleIP (/usr/src/app/routes/api.js:26:68)
    at Object.<anonymous> (/usr/src/app/routes/api.js:27:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/app.js:11:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/bin/www:7:11)
    at Module._compile (module.js:577:32)
npm ERR! Linux 5.4.83-v8
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rest980@2.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by jeremywillans** [comment]
Is this straight after starting the Add-on? or are you trying to access something via the REST API?

**Comment by astranberg** [comment]
> Is this straight after starting the Add-on? or are you trying to access something via the REST API?

Rest980

**Comment by Thib261** [comment]
Hello,

I am having the exact same issue, straight after starting the Add-on.

**Comment by Thib261** [comment]
I solved the issue when i set Firmware to "2"

**Comment by jeremywillans** [comment]
@Thib261 Firmware Version is set to 2 by default when installed in HA?

**Comment by Thib261** [comment]
Correct, but I changed to to 3 thinking this was related to the Roomba software version. My mistake

**Comment by jeremywillans** [comment]
Ah ok, I've updated to README to call this out.

@astranberg - does this fix your issue also?

**Comment by astranberg** [comment]
yes it fixed it.

I do have no output when I goto:
http://IPADDRESS:3000/api/local/info/state

just gives my empty curly brackets.

this occurs while Roomba is running or even after it's finished it's job 

may be unrelated tho....

**Comment by jeremywillans** [comment]
That typcially happens when there is another service "competing" for the MQTT broker that runs on the Robot. Its limited to a single connection at any time. I have historically noticed the the most when using the native "vacuum" integration in parallal as using rest980.

Usually restarting the container should bring it back

**Comment by astranberg** [comment]
Okay thanks man. Do I need to remove or disable the native vacuum integration, reboot 980, and then re run a clean?

**Comment by jeremywillans** [comment]
I would suggest removing the native integration as you dont need it if you are running rest980. Once you restart the container when you browse to the API you should get data without the need for a clean to be running.

You can then follow the instructinos in the README to get this all setup 👍
