### ISSUE TITLE
Help extracting attributes.

### ISSUE THREAD

**Issue by generalk25** [jeremywillans/ha-rest980-roomba#28]

**Comment by generalk25** [comment]
pilotak/homeassistant-attributes

I'm using the above from HACs to display attributes of entities as their own entities. 

It's worked fine till i tried to extract attribute states from your rest980 app. The sensor shows things as a subset of attributes and i have no idea how to reference them. 

Normally we'd do the following....

  - platform: attributes
    friendly_name: "cleaning_time"
    attribute: cleaning_time
    entities:
      - vacuum.jessipooh

However, now that we're doing rest980 instead of the standard roomba integration.. i have no idea how to reference a nested attribute.

  - platform: attributes
    friendly_name: "bin_present"
    attribute: ('sensor.rest980', 'bin')['present']
    entities:
      - sensor.rest980

And that sure as heck doesn't work.

  - platform: attributes
    friendly_name: "bin_present"
    attribute: ('bin')['present']
    entities:
      - sensor.rest980

Nor this.

  - platform: attributes
    friendly_name: "bin_present"
    attribute: present
    entities:
      - sensor.rest980
      
Nor this.

**Comment by jeremywillans** [comment]
Try referencing sensor.vacuum? I have already put these into attributes for easy reference in the LL card and automations.

**Comment by generalk25** [comment]
I can't reference it anymore. Since the integration of rest980 the others just show unavailable all the time.

It's kind of irrelevant anyway since yours gives much more info.

I'd prefer to use yours. You stated you already put them up for easy reference. I see them visually on the lovelace card but i'm not sure how i'd poll their state for an automation.

**Comment by jeremywillans** [comment]
Let me clarify, my integration also has a sensor.vacuum!

It's in the vacuum.yaml file

**Comment by generalk25** [comment]
Oh, neat let me give that a try, thanks jeremy.

**Comment by generalk25** [comment]
It worked great, thanks.

**Comment by generalk25** [comment]
referenced sensor.vacuum
