### ISSUE TITLE
clean map

### ISSUE THREAD

**Issue by generalk25** [jeremywillans/ha-rest980-roomba#30]
![image](https://user-images.githubusercontent.com/84456400/127590935-9c70b35e-edad-488f-ae86-8b53de510738.png)

I'm having the hardest time getting my map to line up.... the roomba just seems to run off the map every time.

here is my current config.... what do i need to adjust or start playing with to keep my roomba from going south of my map?

// ADJUST THESE PARAMETERS
$vacuum_log = 'http://192.168.51.2:3001/vacuum.log'; # Could also be HTTPS
$set_first_coordinate = 0; # Ability to skip initial coordinate(s) if incorrect data logged
$overlay_image = 'floor.png'; # Background Layer
$overlay_walls = false; # Allows overlaying of walls, used in fill mode to cover 'spray'
$walls_image = 'walls.png'; # Walls Image must contain transparent floor
$show_stuck_positions = true; 
$line_thickness = 2; # Default 2, Set to ~60 for Fill Mode
$map_width = 1300; # Ensure overlay and wall images match this size
$map_height = 1300; # Ensure overlay and wall images match this size
$x_offset = 400;
$y_offset = 400;
$flip_vertical = true;
$flip_horizontal = false;
$rotate_angle = 0; # Allows rotating of the roomba lines
$x_scale=1.00; # Allows scaling of roomba x lines
$y_scale=1.00; # Allows scaling of roomba y lines
$ha_rest980 = 'https:192.168.51.2:443/api/states/sensor.rest980';
$ha_token = 'secrettoken';
$ha_timezone = 'America/Chicago'; # Supported Timezones https://www.php.net/manual/en/timezones.php
$ha_text_delimiter = " \n"; # How text is displayed on the map top " \n" --> New Line ## " |" --> Show on one line

**Comment by jeremywillans** [comment]
Can you upload the first say 50ish lines of the vacuum.log file?

**Comment by generalk25** [comment]
Home Assistant notifications (Log started: 2021-07-30T02:25:10.139140+00:00)
--------------------------------------------------------------------------------
(-33, 0, 25)
(-33, 0, 178)
(-929, -519, 93)
(-929, -519, 85)
(-854, -518, 0)
(-713, -519, 0)
(-569, -518, 1)
(-614, -505, 179)
(-753, -505, 178)
(-898, -505, -179)
(-1012, -504, 145)
(-908, -490, 0)
(-764, -492, 2)
(-622, -490, 0)
(-473, -491, 0)
(-318, -490, 0)
(-167, -491, 0)
(-124, -479, 146)
(-267, -476, -179)
(-421, -476, 179)
(-518, -478, -141)
(-539, -478, -172)
(-668, -478, 179)
(-809, -478, 179)
(-962, -478, 179)
(-997, -464, 4)
(-848, -464, 0)
(-705, -464, 0)
(-574, -464, 0)
(-648, -450, 179)
(-791, -451, 179)
(-941, -450, -179)
(-988, -437, 8)
(-841, -437, 0)
(-696, -437, 0)
(-548, -437, 0)
(-399, -437, 0)
(-317, -437, 0)
(-380, -422, -179)
(-532, -423, -179)
(-676, -422, -179)
(-819, -422, -179)
(-973, -423, -179)
(-952, -409, 0)
(-800, -409, 0)
(-655, -409, 0)
(-508, -409, 0)
(-356, -410, 0)
(-398, -395, -178)
(-550, -395, 179)
(-688, -396, -179)
(-829, -398, -178)
(-976, -397, -179)
(-957, -382, 0)
(-805, -383, 0)
(-861, -369, 178)
(-993, -369, -179)
(-908, -356, 0)
(-759, -356, -2)
(-615, -355, 0)
(-522, -356, 58)
(-551, -342, 107)
(-535, -327, 164)
(-568, -334, 163)
(-571, -333, -111)
(-556, -384, -27)
(-465, -395, 0)
(-338, -395, 0)
(-427, -380, 179)
(-549, -380, 179)
(-672, -379, -178)
(-742, -380, -163)
(-737, -401, -98)
(-789, -531, -113)
(-834, -534, -179)
(-985, -534, -179)
(-1001, -534, 179)
(-936, -548, -34)
(-999, -561, -148)
(-986, -588, -175)
(-986, -594, -2)
(-962, -573, 59)
(-958, -567, 156)
(-964, -464, 76)
(-975, -346, 123)
(-904, -346, 0)
(-760, -345, 1)
(-615, -346, 0)
(-520, -346, 0)
(-528, -359, -92)
(-510, -397, -22)
(-493, -474, -143)
(-431, -474, 0)
(-282, -474, 0)
(-128, -474, 0)

**Comment by jeremywillans** [comment]
ok so the first two points are bogus, if you look at the actual number, its completley different from the rest.
not sure why this happens, might just be the robot "working out where it is"

I was able to get the coordinates back on screen adjusting the following

```
$set_first_coordinate = 3; # Ability to skip initial coordinate(s) if incorrect data logged
..
$x_offset = 800;
$y_offset = 1200;
$flip_vertical = false;
```

**Comment by generalk25** [comment]
that gets me much closer.

![image](https://user-images.githubusercontent.com/84456400/127668071-3eb54477-6089-4abf-a4e2-f036f99b17c8.png)

Though i think i'll need to run it again and watch where it actually goes to see how it's mapping... it almost looks like it's 90 degrees off based on this picture.

**Comment by generalk25** [comment]
Also, what method did you follow to come by a map of your home? Do you have any suggestions toward getting the correct dimensions to match the map's 1ft to the roomba's 1ft?

**Comment by generalk25** [comment]
To clarify i just told it to clean the Living room, so it shouldn't have gone anywhere else but i was working and wasn't around to see where it actually went.

**Comment by generalk25** [comment]
rotate angle parameter seems to just make all the roomba lines vanish altogether. I tried 90 and 270 and everything just disappeared.

**Comment by jeremywillans** [comment]
So with rotate lines, the "whole overlay" rotates, not just the lines if that makes sense, so you need to then adjust the offset values.

I suggest running a full clean which give you a complete vacuum.log (and then make a backup copy of this file!) and then keep adjusting the map/offset/rotate/scale options until it looks like your house

**Comment by jeremywillans** [comment]
bump

**Comment by generalk25** [comment]
I get it fixed with your advice
