### ISSUE TITLE
Automation lights

### ISSUE THREAD

**Issue by blakdog1978** [jeremywillans/ha-rest980-roomba#33]
Good morning,
sorry my english but i get help from google ...
given the impossibility of robots to work in the dark I would like to be able to create an automation with lights, let me explain since on the phone app it is displayed in which room the robot is cleaning, I would like to be able to turn on the light automatically when the robot is in the room and consequently turn it off when he leaves it, do you think this is possible?
Thanks...

**Comment by jeremywillans** [comment]
as i stated in the other issue, this component relies on the data from rest980/dorita980 which does not seem to provide the current vacuumed/heading to the room like the app does. 😞 the closest you could get in the automation is to add a step to turn on all the light at the beginning and off again at the end, may not the best outcome however.
