### ISSUE TITLE
[HELP] missing vacuum.log: who, when, where

### ISSUE THREAD

**Issue by unlucio** [jeremywillans/ha-rest980-roomba#37]
Hello,
I can't locate the vacuum.log required by `image.php`
```php
$robot_log = 'http://<ip or fqdn of docker host>:<nginxphpport>/vacuum.log'; # Could also be HTTPS, or mop.log
```

and whenever I try accessing the map images I get this error:

<img width="713" alt="Screenshot 2021-11-26 at 14 58 44" src="https://user-images.githubusercontent.com/778799/143591993-996f8d70-44e2-4447-ad18-430857102f8c.png">

As it refers to `<nginxphpport>` I could expect it to show up in the `vacuum` directory together with the other files from this repo, but no matter how many times I started and stopped my roomba the file never showed up:

<img width="605" alt="Screenshot 2021-11-26 at 14 36 15" src="https://user-images.githubusercontent.com/778799/143589614-d090ccae-1aca-4e0a-9090-3cc73d28e481.png">

I'm quite confused now, can someone help me understand:

- Who is supposed to generate this `vacuum.log`? My guess is `rest980` might generate it, as it's the one talking to the Roomba as far as I understand, but reading the source code doesn't really seem to do that unless [this maps.js file's values route](https://github.com/jeremywillans/hass-addons/blob/master/rest980/routes/map.js), but it's generating a josn and it doesn't have access to the `vacuum`1 directory where all the PHP stuff lives.
- When is the `vacuum.log` generated? Is it created at job-start and then whoever writes in it keeps appending? Or perhaps it's supposed to be generated only at the end of a job?
- Where is it supposed to be written when generated? 

And a final thought just out of curiosity: why `vacuum.log` and then all this? I mean, can't whatever generates the `vacuum.log` directly generate the map since, from what I understood from closed issues I read, that log file is pretty much a list of coordinates?

**Comment by jeremywillans** [comment]
There is an automation which logs the robots position into the vacuum.log file however there is an issue with the 3.20.x firmware from iRobot preventing the positional data from being available in dorita980/rest980

**Comment by unlucio** [comment]
where can I find that automation? my roomba is still on FW 2

**Comment by CoreyJ87** [comment]
> There is an automation which logs the robots position into the vacuum.log file however there is an issue with the 3.20.x firmware from iRobot preventing the positional data from being available in dorita980/rest980

Sooooooo.....Does this just not work anymore or what does that mean?

**Comment by jeremywillans** [comment]
Yeah, hopefully they will fix it ! 🤞

**Comment by jeremywillans** [comment]
Closed pending iRobot

**Comment by ThibautLecrivain** [comment]
so we are still waiting on IRobot to fix it?

**Comment by jeremywillans** [comment]
Unfortunately yes... 😢
