### ISSUE TITLE
php-nginx Docker Image Warning

### ISSUE THREAD

**Issue by felipedlatorre** [jeremywillans/ha-rest980-roomba#38]
When starting the php-nginx  add-on, I get the following warning:

[WARN  tini (8)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.

**Comment by jeremywillans** [comment]
Sorry for the delay, how have you deployed this?

**Comment by jeremywillans** [comment]
bump

**Comment by jensvank** [comment]
I have this same issue. I did it via HACS

**Comment by jeremywillans** [comment]
@jensvank do you have a robot that still supports mapping? as you may not actually need this anymore.

**Comment by jensvank** [comment]
@jeremywillans I have a Roomba 976 with software 2.4.17-138. I thought this one still supports it.
