### ISSUE TITLE
vacuum template with attributes instead template sensors

### ISSUE THREAD

**Issue by wt19** [jeremywillans/ha-rest980-roomba#39]
Hi, first of all many thanks for your great work. Was there a specific reason why you decided to create all the data as template sensors? 

My first impression is that it should be done with a vacuum template by using attribute_templates for all the sensor data. [vacuum.template](https://www.home-assistant.io/integrations/vacuum.template/)

**Comment by jeremywillans** [comment]
I did look at the vacuum template a while back, and noted that some of the attributes only support particular values which didnt work for this deployment. I found using sensor allows free text values for more specifics (such as Mid Dock vs Final Dock)
