### ISSUE TITLE
Invalid Add-on repository!

### ISSUE THREAD

**Issue by ThibautLecrivain** [jeremywillans/ha-rest980-roomba#40]
I get the following message with the URL
"invalid Add-on repository!"

the system give me the following information:
22-01-17 18:52:42 ERROR (MainThread) [supervisor.store] https://github.com/jeremywillans/ha-rest980-roomba.git is not a valid add-on repository

Am i doing something wrong?

**Comment by jeremywillans** [comment]
You need to follow the instructions outlined in the Repo - it unfortunately is not as straight forward as adding this to HA
