### ISSUE TITLE
Regions: null

### ISSUE THREAD

**Issue by mermelmadness** [jeremywillans/ha-rest980-roomba#41]
Hi.  I'm not too good at DIYing this sort of thing, but I'm trying to follow the instructions.  I got to step 5, but after lastCommand the regions listed were always null.  Does it have to be a COMPLETE house clean to get that to appear correctly?

**Comment by jeremywillans** [comment]
Once you have mapped out your house using the iRobot App, then you need to schedule an ordered clean which will list out all the rooms and their respective identifiers. If you initiate full then then it wont (as it will just clean everywhere)

**Comment by jeremywillans** [comment]
Closing - presume working per other Issue.
