### ISSUE TITLE
Errors since Updates of HomeAssistant Supervised

### ISSUE THREAD

**Issue by Neflite** [jeremywillans/ha-rest980-roomba#46]
Hi,

i'm using your cool plugin since a longer time. Everything was working perfectly.
But it seems one of the last HA-Updates broke my addon and i can't fix the 2 errors.

I always get these errors after HA starts.

![image](https://user-images.githubusercontent.com/37070827/192147602-f21f8116-b7f2-4829-9f5f-8b1c64b02a75.png)
![image](https://user-images.githubusercontent.com/37070827/192147627-78c79b6b-1c41-4b0e-9ef9-b9913ed9837c.png)

**Comment by jeremywillans** [comment]
Hi, it looks like you havent updated the secret [vacuum_notify](https://github.com/jeremywillans/ha-rest980-roomba/blob/master/secrets.yaml#L9) with the name of the device you want to send the notification to. 

if you want want to perform notifications, delete the sections as noted [here](https://github.com/jeremywillans/ha-rest980-roomba/blob/master/vacuum.yaml#L568) and [here](https://github.com/jeremywillans/ha-rest980-roomba/blob/master/vacuum.yaml#L608)

**Comment by jeremywillans** [comment]
bump
