### ISSUE TITLE
bbrun sqft/hr/min are missing

### ISSUE THREAD

**Issue by Flodu31** [jeremywillans/ha-rest980-roomba#47]
Hello,

Thank you for this great plugin.

From 3 days now, I have n-a for area/time:

![image](https://user-images.githubusercontent.com/15648175/194871519-acee5935-5a08-451b-b3bc-2b9549067726.png)

After checking logs, it appears that bbrun/sqft and bbrun/hr are missing in the template:

![image](https://user-images.githubusercontent.com/15648175/194871670-41760501-dbb2-453e-8a99-bba1548bc4e2.png)

If I check the api status, they are present in runtimeStats:

![image](https://user-images.githubusercontent.com/15648175/194871748-36d42082-72ae-493c-82df-750b94cf3e0b.png)

Any idea idea? Something has changed in your plugin or in the iRobot API?

Thanks.
Florent

**Comment by jeremywillans** [comment]
Thanks for pointing this out Florent! I have updated vacuum.yaml [here](https://github.com/jeremywillans/ha-rest980-roomba/commit/26ba8819cb6e4b4fd22f22039f44fd9e242ab24c) to account for this change

**Comment by Flodu31** [comment]
Hello @jeremywillans 
I added my mop Braava, and the _2 images doesn't return the runtimeStats apparently,  but it is with the normal image.
Something is missing in the _2 image?
Thanks.
Florent

**Comment by Flodu31** [comment]
I adapted it in the code.
Could be a good idea to update the code. I will push a pull request.

**Comment by jeremywillans** [comment]
@Flodu31 - good call - i have also updated the mop file
