### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by hgelpke** [jeremywillans/ha-rest980-roomba#49]
I'm getting the following error when I check my HA config:

Invalid config for [vacuum]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 36).

Line 36 of my config file is vacuum: !include vacuum.yaml so I'm not sure what to look for

**Comment by jeremywillans** [comment]
this addon does not use the vacuum component - perhaps check that the vacuum.yaml file is correct?

**Comment by hgelpke** [comment]
ah! that's on me. I made that assumption. I'll take it out. Thank you

**Comment by jeremywillans** [comment]
Closing issue - reach out if you still have issues.
