### ISSUE TITLE
more than 2+ roombas?

### ISSUE THREAD

**Issue by bavery79** [jeremywillans/ha-rest980-roomba#50]
Still working on getting this set up, and I see you have installations preconfigured for 1st and 2nd roomba.  How would one go about modifying the installation process for 3rd, 4th & 5th roombas?  :-)

I'm a pretty much a complete noob when it comes to docker & manual installations/configurations so not even sure where to start.

**Comment by jeremywillans** [comment]
are you using the all in one HA image? and configured the custom addon store? i can add a few more, but are they normal or j7 robots?

**Comment by jeremywillans** [comment]
bump

**Comment by spencer-scott** [comment]
Hi Jeremy, I have 2 s9+ Roombas and the Braava j6. I have one of the roombas setup with your add-on and I just finished setting up the Braava as my 2nd vacuum via the rest980_2  Docker Image and the php-nginx_2 Docker Image. I was wondering if was possible to add a 3rd somehow? Wondering what the simplest method is. Thanks!
