### ISSUE TITLE
Buttom to clean a static specific room outside lovelace

### ISSUE THREAD

**Issue by Scarpetta3** [jeremywillans/ha-rest980-roomba#52]
I already write down a similar post on the Home Assistant Forum dedicated topic but I then think that maybe this is a more appropriate place to put down this.
Is it possibile for you to give support or add to the documentation about how can I start to clean a specific room (or two or three of them) by pressing a button outside your beatiful custom card (let's say a buttom-card)? I think is’ something related to call the service automation trigger that start “automation.vacuum_clean_rooms” but I don’t know how to modify the code to change the input from dynamic rooms selection (your lovelace card) to a static one (always that specific room or subset of rooms).

**Comment by jeremywillans** [comment]
I responded on the forum - let me know if that suffices 👍
