### ISSUE TITLE
log stays empty

### ISSUE THREAD

**Issue by prankousky** [jeremywillans/ha-rest980-roomba#53]
Hi,

I just installed `rest980 Docker Image` and `php-nginx Docker Image` through hassOS addons. Configured it - I assume - correctly:
I can

* start the vacuum
* send it to room <x> (for example, living room; it works, because I found the corresponding id, for exaample, `region_id | "5"`
* the lovelace card will show info about the vacuum

![grafik](https://user-images.githubusercontent.com/11297070/219007025-f32d7257-a94c-48aa-936d-b1db09a881c5.png)

However, when I open `http://hassos:3001/image.php` in my browser, I get `No Coordinates found in file, is it reachable and populated? Log file - http://hassos:3001/vacuum.log?`. The logfile (located in `/config/vacuum/vacuum.log` is, indeed, empty.

However, data seems to constantly be loading while the robot runs
![grafik](https://user-images.githubusercontent.com/11297070/219007476-0e44e8a7-c11e-475a-a319-0b844ab65856.png)

After manually starting, then stopping, the vacuum, I get `The image “http://hass:3001/image.php” cannot be displayed because it contains errors.`

While this was the case, the `vacuum.log` actually did contain some data

```
Home Assistant notifications (Log started: 2023-02-15T10:57:38.400271+00:00)
--------------------------------------------------------------------------------
```

I then started another room clean, kitchen this time. Like before, the addon keeps gathering data every second or so. Currently state looks like below, the log from the add-on is beneathh the screenshot.

![grafik](https://user-images.githubusercontent.com/11297070/219015438-d3c0cd26-13e9-4ce2-99ff-0f2f58144bd1.png)

```
GET /api/local/info/state 200 99.853 ms - 5505
GET /api/local/info/state 200 100.873 ms - 5505
GET /api/local/info/state 200 100.763 ms - 5505
GET /api/local/info/state 200 101.093 ms - 5505
GET /api/local/info/state 200 100.803 ms - 5505
GET /api/local/info/state 200 100.964 ms - 5505
GET /api/local/info/state 200 100.886 ms - 5505
GET /api/local/info/state 200 101.080 ms - 5505
GET /api/local/info/state 200 100.941 ms - 5505
GET /api/local/info/state 200 100.756 ms - 5505
GET /api/local/info/state 200 100.869 ms - 5505
GET /api/local/info/state 200 100.734 ms - 5505
GET /api/local/info/state 200 100.088 ms - 5505
GET /api/local/info/state 200 100.834 ms - 5505
GET /api/local/info/state 200 100.782 ms - 5505
GET /api/local/info/state 200 99.881 ms - 5505
GET /api/local/info/state 200 100.772 ms - 5505
GET /api/local/info/state 200 99.882 ms - 5505
```

While this is all happening, the log file stays empty. Could this have anything to do with permissions? I tried `chown 1000:1000 vacuum.log`, but it is currently owned by `root` again (unlike all other files in that directory). Just as a test, I tried `chmod 0777 vacuum.log`, so anybody would be able to write to it. No difference.

![grafik](https://user-images.githubusercontent.com/11297070/219015150-b8819c3f-21e1-4afa-b324-c527b944658c.png)

The api currently shows this as `lastCommand`

![grafik](https://user-images.githubusercontent.com/11297070/219015992-f5a21b09-3cfd-4cce-addc-de1868d5ca40.png)

What can I do to make the map work? Thank you in advance for your help. This project seems so cool, and everything else seems to work fine, so I'm sure this can be fixed as well :)

--

# UPDATE

Just to be sure about permissions, I also did this

* uninstall `php-nginx Docker Image`
* remove `/config/vacuum` directory 
* create `/config/vacuum` directory (directly on the hassos machine)
* clone this repository and copy the contents of `vacuum` into `/config/vacuum`

This time, *all* files were owned by `root`. 

When I manually started my roomba again while watching that folder, I noticed that it did create `vacuum.log`, however, the file stayed at 0 bytes; there was no `log started` or anything like this. At the same time, the rest980 addon did keep updating itself (or querying data from the robot, like in the screenshot / paste above).

So data comes in, but, for some reason, doesn't go into the logfile.

**Comment by jeremywillans** [comment]
Hey @prankousky,

Glad you like the project!

Unfortunately mapping has been broken for a while since iRobot removed the pose (aka location) data from the api.

There is an [issue](https://github.com/koalazak/dorita980/issues/148) open on the dorita980 project (which this leverages), though there's not much progress

**Comment by maceace** [comment]
I can't agree that mapping has been paused
The robot knows well where it is and sends a report of its work from the dock to the cloud when the task is completed. We just don't hear it. 
I don't need to know the online position of the robot, but a quick glance to check the map whether the robot had a problem or not is a desirable function. 
![IMG_20231029_140223](https://github.com/jeremywillans/ha-rest980-roomba/assets/66499150/9b66283d-6550-41b1-b42f-7a6383650941)

**Comment by jeremywillans** [comment]
The mapping data is no longer exposed to the API that rest980 can access. It is present in the App and likely on AWS, but to my knowledge no one has been able to gain access to this data.

**Comment by maa-x** [comment]
The authors of [this paper](https://www.sciencedirect.com/science/article/pii/S2666281723002056) published [this repo](https://github.com/BiTLab-BaggiliTruthLab/PyRoomba) which I successfully tested to retrieve map data for my J7.

I'm not too sure best to integrate it into this project or if we should do it on the dorita980 side first. Thoughts @jeremywillans ?

Here's a map it generated, taken from my J7 just now:

![Image](https://github.com/user-attachments/assets/130f0fd1-eede-42d7-a77d-806dff73b1dd)

**Comment by NicholasFlamy** [comment]
> The authors of [this paper](https://www.sciencedirect.com/science/article/pii/S2666281723002056) published [this repo](https://github.com/BiTLab-BaggiliTruthLab/PyRoomba) which I successfully tested to retrieve map data for my J7.
> 
> I'm not too sure best to integrate it into this project or if we should do it on the dorita980 side first. Thoughts [@jeremywillans](https://github.com/jeremywillans) ?
> 
> Here's a map it generated, taken from my J7 just now:
> 
> ![Image](https://github.com/user-attachments/assets/130f0fd1-eede-42d7-a77d-806dff73b1dd)

Holy moley this is great news. I hate that iRobot continues to collect data on your private space and then started hiding that private data from you. So f*cked up. I'll have to see if I can make use of this. Also, if anyone knows a brand of robot vacuum that respects you and allows offline use with connection to your own server let me know.
