### ISSUE TITLE
Error installing, does this support the i8+?

### ISSUE THREAD

**Issue by seseyffe** [jeremywillans/ha-rest980-roomba#57]
HI Jeremy,

i was impressed with your documentation and design and wanted to incorporate this into my HA but ran into an issue.  i didn't notice that this didn't mention the i8+ model, maybe that was the problem?

![image](https://user-images.githubusercontent.com/48224654/231871714-41259d29-098a-4eac-881a-e74c56c932b6.png)

I'd apperciate any advice or help if changes can be made to support.. thank you, Steve

**Comment by jeremywillans** [comment]
Hi there, I believe the i8 is just the same as the i7 so this should work!

You just need to make sure you are putting your robot in pairing mode by holding the home button until it flashes?

**Comment by seseyffe** [comment]
I was able to get this work, thank you so much!
