### ISSUE TITLE
More of a Question

### ISSUE THREAD

**Issue by BramWarrick** [jeremywillans/ha-rest980-roomba#6]
I see what's been done here and it covers a LOT of what I'd like to do with my i9+. 

I've read through the Readme and understand this is:
* targeted to the i7+
* a multi-step process to get everything working

Before I jump in and invest a few hours is this expected to work for the i9 series too? I kind of expect the API to be the same - or very close to it (features differ some).

What are your thoughts on me trying this out?

**Comment by jeremywillans** [comment]
People have this deployed and working using an s9+ 👍

**Comment by BramWarrick** [comment]
Diving in, then!

It's clear you've put a lot of time and energy into this - and it looks great! I just wish I'd found this earlier. Please feel free to close the issue. :-)

**Comment by jeremywillans** [comment]
Thanks! Reach out if you run into any dramas! :)

[Here](https://community.home-assistant.io/t/irobot-roomba-i7-configuration-using-rest980/161175) is the best place to get help from myself and other running this solution 🍻
