### ISSUE TITLE
how to control roomba via automation now

### ISSUE THREAD

**Issue by ecto1a2003** [jeremywillans/ha-rest980-roomba#61]
i need to be able to stop the roomba and dock it via automation. how do i do that? are there example rest commands?

**Comment by jeremywillans** [comment]
you can use RESTful Commands to issue this
just need to incorporate that into an automation as the action

supported commands here are `start`,`pause`,`resume`,`stop`,`dock`

when docked, you can issue the empty (for + models) with the dock command. 

```
service: rest_command.vacuum_action
data:
  command: dock
```
