### ISSUE TITLE
couple of questions about handling mulitple roomba's

### ISSUE THREAD

**Issue by dixi83** [jeremywillans/ha-rest980-roomba#64]
Hi Jeremy,

Thank you for you work! While walking through your steps (currently at step 6, so far so good), I have some questions about handling multiple robot's. We have 2 i7+'s running here and planning to get a 3rd one.  I am running HAOS on a proxmox virtual machine

1. ~~how to handle secrets.yaml? I only see options to configure 1 device...~~
2. ~~do i need to create a separate directory for each robot, containing the PHP files?~~
3. is it possible to create a 3rd set of php-nginx and the rest980 addons?

**Comment by dixi83** [comment]
I figured out 1 and two (sorry I am quite new to home assistant...) I was quite an adventure and I learned a lot! ;)
about nr.3... I think if I fork your repo and duplicate the nginx and rest980 folders I'll be good to go?

**Comment by jeremywillans** [comment]
Hi @dixi83, 

You wont likely need the nginx instance as the mapping api has been removed
But essentially yes, creating another rest980 instance will allow you to accomplish three roombas 👍

**Comment by dixi83** [comment]
Thank you, I was already trying to remove the nginx instances, I'll figure that out. It is all working at the moment so, many thanks for your work!
