### ISSUE TITLE
roomba-vacuum-card isn't displayed anymore after update to Home Assistant OS 12.0

### ISSUE THREAD

**Issue by Falfango** [jeremywillans/ha-rest980-roomba#66]
As the title says the vacuum-card is no longer displayed after update to Home Assistant OS 12.0 on the dashboard. In edit mode of the dashobard it lets choose the sensor and some switches, but no preview is visible.

**Comment by jeremywillans** [comment]
Are you sure its been loaded via HACS? I dont use HAOS so I am not sure why this isnt working. I just upgraded to 2024.3 and it is still working fine for me 🤷‍♂️
